### ISSUE TITLE
[BUG] keyError: 'RUN'

### ISSUE THREAD

**Issue by Thanakron1997** [saketkc/pysradb#168]
When I running this command:

```
pysradb metadata PRJNA186035 --detailed --expand --desc  --assay --saveto <output_path>
```
```
```

and it give this error
```
Traceback (most recent call last):
  File "/home/va/anaconda3/bin/pysradb", line 10, in <module>
    sys.exit(parse_args())
  File "/home/va/anaconda3/lib/python3.9/site-packages/pysradb/cli.py", line 1202, in parse_args
    metadata(
  File "/home/va/anaconda3/lib/python3.9/site-packages/pysradb/cli.py", line 79, in metadata
    df = sradb.sra_metadata(
  File "/home/va/anaconda3/lib/python3.9/site-packages/pysradb/sraweb.py", line 562, in sra_metadata
    run_sets = record["RUN_SET"]["RUN"]
KeyError: 'RUN
```

**Desktop (please complete the following information):**
 - OS:  Linux mint 20.3
 - Python version 3.9.12

Try in colab
![image](https://user-images.githubusercontent.com/100277150/205333599-f242d4c7-b589-41be-b562-093e061fd8a5.png)

**Comment by Thanakron1997** [comment]
That work for me. Thank you!
