### ISSUE TITLE
ValueError: Value must be a nonnegative integer or None

### ISSUE THREAD

**Issue by zhouxw27** [saketkc/pysradb#193]
* pysradb version: 2.0.2  
* Python version: 3.10.8
* Operating System: linux ubuntu

### Description

Thank you for the work. This is my first time using pysradb to download SRA data. However, this error happened. 
I don't know how to solve it. Could someone help me? Thanks for your time.

### What I Did

```
pysradb download -p SRP162234

Checking download URLs
The following files will be downloaded: 

Traceback (most recent call last):
  File "/home/***/miniconda3/envs/***/bin/pysradb", line 10, in <module>
    sys.exit(parse_args())
  File "/home/***/miniconda3/envs/***/lib/python3.10/site-packages/pysradb/cli.py", line 1189, in parse_args
    download(
  File "/home/***/miniconda3/envs/***/lib/python3.10/site-packages/pysradb/cli.py", line 125, in download
    sradb.download(
  File "/home/***/miniconda3/envs/***/lib/python3.10/site-packages/pysradb/sradb.py", line 1538, in download
    pd.set_option("display.max_colwidth", -1)
  File "/home/***/miniconda3/envs/***/lib/python3.10/site-packages/pandas/_config/config.py", line 261, in __call__
    return self.__func__(*args, **kwds)
  File "/home/***/miniconda3/envs/***/lib/python3.10/site-packages/pandas/_config/config.py", line 160, in _set_option
    o.validator(v)
  File "/home/***/miniconda3/envs/***/lib/python3.10/site-packages/pandas/_config/config.py", line 882, in is_nonnegative_int
    raise ValueError(msg)
ValueError: Value must be a nonnegative integer or None
```

**Comment by saketkc** [comment]
Thanks for the bug report. This has been fixed in [pysradb v2.1.0](https://pypi.org/project/pysradb/2.1.0/). I would recommend updating your pysradb installation and reopen this if you still face issues.
