### ISSUE TITLE
Failure of metadata

### ISSUE THREAD

**Issue by andrewdavidsmith** [saketkc/pysradb#222]
**Describe the bug**
Failure of `metadata` on some SRA accessions when `VALUE` is not a key for `value_x`.

**To Reproduce**
```console
$ pysradb metadata --detailed ERP009821
Traceback (most recent call last):
  File "/code/external/pysradb/.venv/bin/pysradb", line 8, in <module>
    sys.exit(parse_args())
             ^^^^^^^^^^^^
  File "/code/external/pysradb/pysradb/cli.py", line 1173, in parse_args
    metadata(
  File "/code/external/pysradb/pysradb/cli.py", line 69, in metadata
    df = sradb.sra_metadata(
         ^^^^^^^^^^^^^^^^^^^
  File "/code/external/pysradb/pysradb/sraweb.py", line 596, in sra_metadata
    value = value_x["VALUE"]
            ~~~~~~~^^^^^^^^^
KeyError: 'VALUE'
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version 3.12

**Additional context**
pysradb version: clone at 35dbf24

**Comment by saketkc** [comment]
This seems to be fixed now:

```
pysradb metadata --detailed ERP009821 
run_accession   study_accession study_title     experiment_accession    experiment_title        experiment_desc organism_taxid  organism_name   library_name    library_strategy        library_source  library_selection       library_layout  sample_accession        sample_title       biosample       bioproject      instrument      instrument_model        instrument_model_desc   total_spots     total_size      run_total_spots run_total_bases run_alias       ebi_url ebi_free_egress ebi_access_type experiment_alias        sra accession      sample name     animal age at collection        developmental stage     health status at collection     material        organism part   project specimen collection date        specimen collection protocol    submission description  submission identifier   submission title   assay type      sample storage  sample storage processing       sampling to preparation interval        experimental protocol   extraction protocol     library preparation location    library preparation location longitude  library preparation location latitude      library preparation date        sequencing location     sequencing location longitude   sequencing location latitude    sequencing date experiment target       library generation pcr product isolation protocol       library generation protocol     library selection  public_filename public_url      public_size     public_date     public_md5      public_version  public_semantic_name    public_supertype        public_sratoolkit       aws_url aws_free_egress aws_access_type ncbi_url        ncbi_free_egress        ncbi_access_type   gcp_url gcp_free_egress gcp_access_type rna preparation 3' adapter ligation protocol    rna preparation 5' adapter ligation protocol    preparation reverse transcription protocol      read strand     rna purity - 260:280 ratio      rna purity - 260:230 ratio rna integrity number    bisulfite conversion protocol   pcr product isolation protocol  bisulfite conversion percent    restriction enzyme      min fragment size selection range       max fragment size selection range       pool creation date      pool creation protocol     material        ena_fastq_http  ena_fastq_http_1        ena_fastq_http_2        ena_fastq_ftp   ena_fastq_ftp_1 ena_fastq_ftp_2
ERR789169       ERP009821       Porcine Transcriptome and Methylome Map ERX779332       Illumina HiSeq 2000 sequencing  Illumina HiSeq 2000 sequencing  9823    Sus scrofa      Fat RRBS        Bisulfite-Seq   GENOMIC Reduced Representation  SINGLE  ERS682350       <NA>       SAMEA3303525    PRJEB8784       Illumina HiSeq 2000     Illumina HiSeq 2000     ILLUMINA        0       0       <NA>    <NA>    ena-RUN-UNIVERSITY OF ILLINOIS CHAMPAIGN-URBANA-13-03-2015-07:31:19:386-1       http://ftp.sra.ebi.ac.uk/vol1/run/ERR789/ERR789169/Fat_RRBS.bam    worldwide       anonymous       ena-EXPERIMENT-UNIVERSITY OF ILLINOIS CHAMPAIGN-URBANA-13-03-2015-07:31:19:386-1        ERS682350       SSC_UIUC_FAT    3       adult   normal  specimen from organism  subcutaneous adipose tissue     FAANG   2004-05-26https://data.faang.org/api/fire_api/samples/UIC_SOP_Tissue_Collection_Protocol_20170412.pdf      Eight tissues (Fat, Heart, Kidney, Liver, Muscle, Lung, Lymph Node, Spleen) from the female duroc chosen for sequencing of the pig genome sequence (Sscrofa10.2).       GSB-5171   UIUC-FAANG-SCHACHTSCHNEIDER-Pig-070417  <NA>    <NA>    <NA>    <NA>    nan     <NA>    <NA>    <NA>    <NA>    nan     <NA>    <NA>    <NA>    nan     <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>       <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    nan     nan     nan     <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    http://ftp.sra.ebi.ac.uk/vol1/fastq/ERR789/ERR789169/ERR789169.fastq.gz            <NA>    era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/ERR789/ERR789169/ERR789169.fastq.gz
ERR789170       ERP009821       Porcine Transcriptome and Methylome Map ERX779333       Illumina HiSeq 2000 sequencing  Illumina HiSeq 2000 sequencing  9823    Sus scrofa      Heart RRBS      Bisulfite-Seq   GENOMIC Reduced Representation  SINGLE  ERS682351       <NA>       SAMEA3303526    PRJEB8784       Illumina HiSeq 2000     Illumina HiSeq 2000     ILLUMINA        0       0       <NA>    <NA>    ena-RUN-UNIVERSITY OF ILLINOIS CHAMPAIGN-URBANA-13-03-2015-07:31:19:387-2       http://ftp.sra.ebi.ac.uk/vol1/run/ERR789/ERR789170/Heart_RRBS.bam  worldwide       anonymous       ena-EXPERIMENT-UNIVERSITY OF ILLINOIS CHAMPAIGN-URBANA-13-03-2015-07:31:19:387-2        ERS682351       SSC_UIUC_HEART  3       adult   normal  specimen from organism  heart   FAANG   2004-05-26      https://data.faang.org/api/fire_api/samples/UIC_SOP_Tissue_Collection_Protocol_20170412.pdf        Eight tissues (Fat, Heart, Kidney, Liver, Muscle, Lung, Lymph Node, Spleen) from the female duroc chosen for sequencing of the pig genome sequence (Sscrofa10.2).       GSB-5171        UIUC-FAANG-SCHACHTSCHNEIDER-Pig-070417     <NA>    <NA>    <NA>    <NA>    nan     <NA>    <NA>    <NA>    <NA>    nan     <NA>    <NA>    <NA>    nan     <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>       <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    nan     nan     nan     <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    http://ftp.sra.ebi.ac.uk/vol1/fastq/ERR789/ERR789170/ERR789170.fastq.gz            <NA>    era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/ERR789/ERR789170/ERR789170.fastq.gz
ERR789171       ERP009821       Porcine Transcriptome and Methylome Map ERX779334       Illumina HiSeq 2000 sequencing  Illumina HiSeq 2000 sequencing  9823    Sus scrofa      Kidney RRBS     Bisulfite-Seq   GENOMIC Reduced Representation  SINGLE  ERS682352       <NA>       SAMEA3303527    PRJEB8784       Illumina HiSeq 2000     Illumina HiSeq 2000     ILLUMINA        0       0       <NA>    <NA>    ena-RUN-UNIVERSITY OF ILLINOIS CHAMPAIGN-URBANA-13-03-2015-07:31:19:387-3       http://ftp.sra.ebi.ac.uk/vol1/run/ERR789/ERR789171/Kidney_RRBS.bam worldwide       anonymous       ena-EXPERIMENT-UNIVERSITY OF ILLINOIS CHAMPAIGN-URBANA-13-03-2015-07:31:19:387-3        ERS682352       SSC_UIUC_KIDNEY 3       adult   normal  specimen from organism  kidney  FAANG   2004-05-26      https://data.faang.org/api/fire_api/samples/UIC_SOP_Tissue_Collection_Protocol_20170412.pdf        Eight tissues (Fat, Heart, Kidney, Liver, Muscle, Lung, Lymph Node, Spleen) from the female duroc chosen for sequencing of the pig genome sequence (Sscrofa10.2).       GSB-5171        UIUC-FAANG-SCHACHTSCHNEIDER-Pig-070417     <NA>    <NA>    <NA>    <NA>    nan     <NA>    <NA>    <NA>    <NA>    nan     <NA>    <NA>    <NA>    nan     <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>       <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    nan     nan     nan     <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    <NA>    http://ftp.sra.ebi.ac.uk/vol1/fastq/ERR789/ERR789171/ERR789171.fastq.gz            <NA>    era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/ERR789/ERR789171/ERR789171.fastq.gz
```
