### ISSUE TITLE
Probleme with pip from metadata to download

### ISSUE THREAD

**Issue by jeammimi** [saketkc/pysradb#41]
* pysradb version: 0.10.4
* Python version:3.7.7
* Operating System: linux

### Description
I have a problem when using the pipe from metadata to download.
It seems that the input from metadata is not well parsed into download.
And the download command  use the column run_total_spots thinking that it is 
the column run_accession 

### What I Did

```
pysradb metadata SRP026303 --assay | grep 'study\|AUY077' | pysradb download
```

This error occurs

```
Traceback (most recent call last):
  File "/home/jeanmichel/miniconda3/envs/alignment/bin/pysradb", line 8, in <module>
    sys.exit(parse_args())
  File "/home/jeanmichel/miniconda3/envs/alignment/lib/python3.7/site-packages/pysradb/cli.py", line 1051, in parse_args
    download(args.out_dir, args.db, args.srx, args.srp, args.skip_confirmation)
  File "/home/jeanmichel/miniconda3/envs/alignment/lib/python3.7/site-packages/pysradb/cli.py", line 141, in download
    protocol=protocol,
  File "/home/jeanmichel/miniconda3/envs/alignment/lib/python3.7/site-packages/pysradb/sradb.py", line 1299, in download
    + ".sra"
  File "/home/jeanmichel/miniconda3/envs/alignment/lib/python3.7/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/jeanmichel/miniconda3/envs/alignment/lib/python3.7/site-packages/pandas/core/accessor.py", line 187, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/jeanmichel/miniconda3/envs/alignment/lib/python3.7/site-packages/pandas/core/strings.py", line 2039, in __init__
    self._inferred_dtype = self._validate(data)
  File "/home/jeanmichel/miniconda3/envs/alignment/lib/python3.7/site-packages/pandas/core/strings.py", line 2096, in _validate
    raise AttributeError("Can only use .str accessor with string values!")pysradb download 
AttributeError: Can only use .str accessor with string values!
```
I took a look at the parsing but it seems not straightforward to correct it

A work around this issue could be something like that:

pysradb metadata SRP026303 --assay --saveto tmp.txt && cat tmp.txt | grep 'study\|AUY077' > tmp.txt  &&  pysradb download  --input_file tmp.txt

**Comment by saketkc** [comment]
Thanks @jeammimi for the report. This probably seems to arise from a confusing flag `--assay` that is no longer required if you are using the `SRAweb` mode.

Instead if you want to pipe the output to download, you should be using the `--detailed` flag:

```
pysradb metadata SRP026303 --detailed | grep 'study\|AUY077' | pysradb download
```

We are working on getting the docs in a better shape. Feel free to reopen if you face any issues with the above command.

**Comment by jeammimi** [comment]
Yes it works. Thank you, and thank you for your project, that will help improving reproducibility
of biological analysis !
Best
