### ISSUE TITLE
[BUG] KeyError: 'EXPERIMENT_PACKAGE_SET'

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [saketkc/pysradb#68]
**Describe the bug**
version 0.11.1-dev0
```
import pysradb

db = pysradb.SRAweb()
db.sra_metadata("SRP098789", detailed=True)

Traceback (most recent call last):
  File "script", line 4, in <module>
    db.sra_metadata("SRP098789", detailed=True)
  File "/home/maarten/anaconda3/envs/seq2science/lib/python3.7/site-packages/pysradb/sraweb.py", line 456, in sra_metadata
    efetch_result = self.get_efetch_response("sra", srp)
  File "/home/maarten/anaconda3/envs/seq2science/lib/python3.7/site-packages/pysradb/sraweb.py", line 323, in get_efetch_response
    response = xmltodict.parse(request_text)["EXPERIMENT_PACKAGE_SET"][
KeyError: 'EXPERIMENT_PACKAGE_SET'
```

**Comment by Maarten-vd-Sande** [comment]
I am also pretty sure that today I got `KeyError: 'EXPERIMENT_PACKAGE'` before (the key one line farther), but I guess that's related to this one

**Comment by Maarten-vd-Sande** [comment]
A call to efetch gave me this result, so it seems like ncbi is down-ish. Would be nice if pysradb catches this more "gracefully", but that's a minor detail.

```
500 Internal Server Error

No do_post output returned from 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=sra&query_key=1&WebEnv=MCID_5f6236a16761b17fe3514db7&rettype=&retmode=text&retstart=0&retmax=1&edirect_os=linux&edirect=11.0&tool=edirect&email=jenkins@ocimum'
```

**Comment by saketkc** [comment]
Thanks @Maarten-vd-Sande, this indeed is arising from NCBI (I was unable to replicate it locally just now). #69 should hopefully throw out better failure messages.

**Comment by Maarten-vd-Sande** [comment]
Awesome! Thanks for these fast fixes and replies :zap: !
